mezo-org/validator-kit

docker/v-kit.sh

Closes: https://github.com/mezo-org/validator-kit/issues/3 (by the way)
`./v-kit.sh export-private-key` prints the private key for validator.
That function can be used in pipes, and as follows:
```
key="$(./v-kit.sh export-private-key)"
```
`build` function has been removed since it's not needed anymore.

docker: Add export-private-key function to v-kit.sh

---

docker/v-kit.sh

`start` pulls all images defined in compose.yaml. We need to make sure that CLI image is already available locally. Otherwise it fails with:
```
✘ cli Error          pull access denied for local/mezod-cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

docker: Build CLI image before start

---

docker/README.md

This pull request includes a small change to the `docker/README.md` file. The change clarifies the ownership requirements for the local directory used by the Docker container.
Documentation update:
* [`docker/README.md`](diffhunk://#diff-da8fcbe728a9172b578e5d754f8e2df214c658c4321f610e63dd68bea828ab49L60-R65): Added instructions to ensure the local directory is owned by the user with UID 65532 and GID 65532, including an example command to change ownership.

fix(docker): set permissions for storage dir

---

native/v-kit.sh
tools/hardhat/submit-application.sh

Closes https://github.com/mezo-org/validator-kit/issues/8
- Validator consensus address -> Validator consensus pubkey
- Validator network address -> Validator consensus address
- Moniker is extracted now from `validator-info` command, not from the `testnet.env` file
- Echoing proper namings

Adjusting validator info namings and how we extract moniker

---

.github/workflows/checks-pr.yaml
.github/workflows/checks.yaml
.github/workflows/helm-chart-release.yaml
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md

Add GHA for checking if the Helm chart release already exists. Any change in the Helm chart requires to increase the version. Example fail: https://github.com/mezo-org/validator-kit/actions/runs/12196696106/job/34024809367?pr=23
[Previous PR](https://github.com/mezo-org/validator-kit/pull/22) failed because of this.

Improve Helm chart release GHA

---

docker/compose.yaml
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/templates/configmap.yaml
helm-chart/mezod/templates/service-private.yaml
helm-chart/mezod/templates/service-public.yaml
helm-chart/mezod/templates/serviceaccount.yaml
helm-chart/mezod/templates/statefulset.yaml
helm-chart/mezod/values.yaml

This PR
- adds labels to all resources
- adds Skip `connect-sidecar` to the Statefulset without some default parameters.
Skip is not yet implemented in `mezod`. However, as a preparation step `connect-sidecar` can be running.
This PR has been tested by me on my validator.
Connect-sidecar returns:
```{"level":"error","ts":"2024-12-04T12:10:29.278Z","caller":"marketmap/fetcher.go:104","msg":"failed to query market map module on node","pid":1,"process":"oracle","fetcher":"marketmap_api","error":"rpc error: code = Unimplemented desc = unknown service connect.marketmap.v2.Query"}```
but I assume it's ok for now since it's not yet implemented on the `mezod` side.

Add connect-sidecar to Helm chart

---

docker/README.md
docker/testnet.env.example
docker/v-kit.sh

Adjust README.md, testnet.env.example, and v-kit.sh to include instructions on how to generate a new mnemonic phrase.
This is because of https://github.com/mezo-org/mezod/pull/354

Adjust Docker deployment for mnemonic

---

.github/workflows/checks-pr.yaml

Check for Helm chart must be running only when concern to helm charts folder.

Fix GHA for PRs

---

native/README.md
native/testnet.env.example
native/v-kit.sh

> [!NOTE]
> This is a follow-up PR for the mezo `entrypoint.sh` edit in `mezod` repo (https://github.com/mezo-org/mezod/pull/354).
The following changes were made:
- Mnemonic should be generated BEFORE running the install script (`v-kit mnemonic` function added)
- Enable recovery mode in `mezod init` and `mezod keys add`
- Add `pruning=nothing` to cosmos sdk config (`app.toml`)
- Add MEZOD_KEYRING_MNEMONIC variable in `testnet.env.example`
- Update documentation
Example output for `./v-kit.sh mnemonic`:
```
------------------------------------------------
Reading configuration from environment files
------------------------------------------------
Generating mnemonic...
Save it into your environment file under the variable MEZOD_KEYRING_MNEMONIC
---BEGIN MNEMONIC---
mention maid fashion …
```

Recovery mode for native kit + mnemonic generation refactor

---

docker/README.md
docker/testnet.env.example
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml
native/README.md
native/testnet.env.example
native/v-kit.sh

Depends on https://github.com/mezo-org/mezod/pull/357
Closes: #24 
Refs https://linear.app/thesis-co/issue/ENG-415/support-custom-p2p-ports-in-the-validator-kit
~~Note. Please do not merge until we have a new image/binary cut from mezod repo. Leaving it as a draft for now.~~ We have a new `[v0.2.0-rc2](https://github.com/mezo-org/mezod/releases/tag/v0.2.0-rc2)` image that contains needed dependency.
Some of the validators might want to set a custom p2p port in their node configs. We need to allow them doing so. Adjusted custom p2p port setup for docker, native and helm-chart approaches.

Adding custom port setup for P2P connection

---

helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/templates/statefulset.yaml
helm-chart/mezod/values.yaml

Changes
- bump Docker image and Helm chart version
- Fix for environment variables. They must be strings, because Helm fails. `| quote` will do `"123"` from `123`.

Bump and fix chart

---

helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml
native/testnet.env.example

We are about to roll out the Connect oracle on Mezo testnet. We need to ensure existing validators can seamlessly connect with their Connect sidecars once the upgrade happens.
Pull request https://github.com/mezo-org/mezod/pull/359 introduces the following on the `mezod` side:
- The `init` command now adds the oracle-specific config to `app.toml`.
- The `start` command exposes oracle-specific flags (`--oracle.*` family) with default values.
- The `customize_configuration` of the `entrypoint.sh` enables the oracle by default and allows setting its address using the `MEZOD_ORACLE_ORACLE_ADDRESS` env (naming adjusted to the `app.toml` param according to Vyper's convention). If this env is not set, the default value of `connect-sidecar:8080` is used.
To make everything work, we are …

Adjust V-Kit to the Connect oracle changes

---

helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/templates/statefulset.yaml
helm-chart/mezod/values.yaml

Here we parametrize the `imagePullPolicy` for `mezod` and Connect Docker images. There are some use cases where this setting is beneficial. We are also setting the `Always` policy as default to make sure containers always use the freshest image.

Parametrize image pull policy

---

native/v-kit.sh

This is a small fix for setting pruning parameter in `mezod toml set` section. From `-v "pruning=nothing"` to `-v pruning="nothing"`.

Set pruning parameter in a correct way

---

helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

Here we bump the `mezod` image to the latest version to include recent improvements. We also bump the chart version to v1.0.1

Bump mezod and Ethereum sidecar to v0.3.0-rc2

---

native/v-kit.sh

The native V-Kit enforces different values for consensus timeouts. The Docker/Helm variants use the CometBFT defaults. Here we align the native V-Kit to use the default values as well.

Adjust consensus timeouts in the native V-Kit

---

README.md
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

Here we bump the `mezod` version to `v0.4.0-rc0` and release a new version of the Helm chart.

Bump mezod to v0.4.0-rc0

---

docker/README.md
helm-chart/mezod/README.md
manual/README.md
native/README.md

References: https://linear.app/thesis-co/issue/TET-17/enforce-websocket-rpc-in-the-ethereum-sidecar
This PR updates documents describing launching Ethereum sidecar.
When launching Ethereum sidecar we must use a WebSocket URL for the `--ethereum-sidecar.server.ethereum-node-address` option (e.g.: `wss://eth-sepolia.g.alchemy.com/v2/<your-key>`). This will soon be enforced by a check in Ethereum sidecar.

Updated docs for launching Ethereum sidecar

---

helm-chart/mezod/README.md.gotmpl

This PR is a follow-up to: https://github.com/mezo-org/validator-kit/pull/48 which introduced a CI error.
We need to update the Helm chart README.

Updated Helm docs

---

README.md

References: https://linear.app/thesis-co/issue/TET-28/the-v050-matsnet-fork
NOTE: Leaving it as a draft PR until we cut `v0.5.0` mezod. Please do not merge until then.
Closes: https://linear.app/thesis-co/issue/TET-137/expose-a-cli-command-to-submit-validator-application
Added description for validators around ways they can submit their PoA applications. Additionally to the Hardhat approach wrapped by `submit-application.sh` script there will be another option to use `mezod` binary. Binary CLI command
```bash
./build/mezod --home=<mezod_home_path> poa submit-application <key_name>
```
will be available starting from mezod `v0.5.0` release.

Binary application submission docs

---

README.md
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-28/the-v050-matsnet-fork
Here we bump the `mezod` version to `v0.5.0-rc0` and release a new version of the Helm chart. Moreover, we add some minor improvements to the root README.

Bump mezod to v0.5.0-rc0

---

README.md

Here we add the missing info about the recent v0.5.0 fork.

Update version ordering guide for block sync from genesis

---

README.md
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-258/the-v060-matsnet-fork
Here we bump the `mezod` version to `v0.6.0-rc0` and release a new version of the Helm chart.

Bump mezod to v0.6.0-rc0

---

README.md
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-382/the-v070-matsnet-fork
Here we bump the mezod version to v0.7.0-rc0 and release a new version of the Helm chart.

Bump mezod to v0.7.0-rc0

---

README.md

References: https://linear.app/thesis-co/issue/TET-382/the-v070-matsnet-fork
[The last version of this release line is `v0.6.0-rc2`](https://github.com/mezo-org/mezod/tags) and it should be used during the block sync process. By mistake, we put `v0.6.0-rc1` here so we are changing it.

Fix last `v0.6.0-rc*` version in the README

---

README.md
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-701/the-v100-rc1-matsnet-upgrade
Here we bump the `mezod` version to `v1.0.0-rc1` and release a new version of the Helm chart.

Bumping helm chart version preping for v1.0.0-rc1

---

helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md

> [!NOTE]
> This is a new chart version for initContainers fix that prevents volume mounting errors on mezod startup.

bump mezo chart version

---

README.md

For some validators a default localnode url `http://127.0.0.1:8545` won't work for application submission. It can be fixed by adding `--rpc-url <url>` flag pointing to a valid RPC url. This info should also be included in the `--help` of the command itself, but for the time being as we are onboarding more validators, we can add this info in the docs here.

Adding rpc-url optional flag description

---

README.md
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-1126/the-v200-mainnet-upgrade
Here we bump the mezod version to v2.0.0 and release a new version of the Helm chart.

Bump mezod to v2.0.0

---

helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-1207/the-v201-mezod-release
Here we bump the mezod version to v2.0.1 and release a new version of the Helm chart.

Bump mezod to v2.0.1

---

README.md

References: https://linear.app/thesis-co/issue/TET-1299/the-v300-mezod-release-candidate-testnet
Here we update the version ordering for testnet to include the upcoming v3.x.x release.

Update testnet version ordering

---

README.md
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-1300/the-v300-mezod-release-mainnet
Here we bump the mezod version to v3.0.0 and release a new version of the Helm chart.

Bump mezod to v3.0.0

---

helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/values.yaml

References: https://linear.app/thesis-co/issue/TET-1396/the-v301-mezod-release
Here we bump the mezod version to v3.0.1 and release a new version of the Helm chart.

Bump mezod to v3.0.1

---

docker/compose.yaml
helm-chart/mezod/Chart.yaml
helm-chart/mezod/README.md
helm-chart/mezod/templates/statefulset.yaml
manual/README.md
native/v-kit.sh

Closes: https://linear.app/thesis-co/issue/TET-1198/adjustments-in-the-validator-kit
The Ethereum sidecar gained some new flags:
- `ethereum-sidecar.server.assets-unlocked-endpoint` -> Address of the mezod gRPC endpoint used to get AssetsUnlocked events emitted on the Mezo chain
- `keyring-backend` -> Backend used to store the operator key
- `key-name` -> Name of the operator key to extract from keyring (mandatory for bridge validator nodes, optional for other node types)
Those flags are necessary to make the sidecar compatible with the bridge out flow. In this PR, we are adjusting all variants of the V-Kit to set them properly for all validators by default, regardless whether they are promoted to bridge validators or not. Such an approach will simplify future maintenance.

Adjust the V-Kit to Ethereum sidecar changes related to bridge out
